name: Update Footer Year

on:
  schedule:
    - cron: '0 0 1 1 *'  # Every Jan 1st at 00:00 UTC
  workflow_dispatch:      # Also allow manual runs

jobs:
  update-year:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update <em id="date"> year
        run: |
          CURRENT_YEAR=$(date +"%Y")
          echo "Updating year to $CURRENT_YEAR"
          sed -i -E 's|<em id="date">[0-9]{4}</em>|<em id="date">'$CURRENT_YEAR'</em>|' index.html

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add index.html
          git commit -m "Update footer year to $CURRENT_YEAR" || echo "No changes to commit"
          git push
